[package]
name = "cannon-heap"
authors = ["Willem Olding <willemolding@gmail.com>"]
description = "A heap allocator suitable for Cannon MIPS executables"
license = "LGPL-3.0"
version = "0.1.0"
edition = "2021"

[dependencies]
linked_list_allocator = "0.10.5"
